# Generated by Django 5.1.2 on 2024-11-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
        ("users", "0004_alter_payments_options_alter_user_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payments",
            new_name="Payment",
        ),
    ]
