# Generated by Django 5.1.2 on 2024-11-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CoursePurchase",
        ),
    ]
