# Generated by Django 5.1.2 on 2024-11-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_delete_coursepurchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Статус активности"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата последнего входа"
            ),
        ),
    ]
