# Generated by Django 5.1.2 on 2024-11-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="sign_up",
            field=models.BooleanField(default=False, verbose_name="Подписка"),
        ),
    ]
