# Generated by Django 5.1.2 on 2024-11-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_subscription_sign_up"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="sign_up",
        ),
    ]
